export { default as App } from './app'
export { default as LogIn } from './log-in'
export { default as Settings } from './settings'
export { default as PrivacyPolicy } from './privacy-policy'
export { default as TermsOfService } from './terms-of-service'
export { default as NotFound } from './not-found'
